- name: Install Tomcat Application server
  hosts: all
  tasks:
    - name: Ensure tomcat is installed
      yum:
        name: tomcat
        state: present
    - name: something
      template:
        src: default.template
        dest: /tmp/default.conf
    - name: Ensure tomcat service is enabled and started
      service:
        name: tomcat
        enabled: yes
        state: started
    - name: Download Java application and restart Tomcat
      get_url:
        url: https://tomcat.apache.org/tomcat-6.0-doc/appdev/sample/sample.war
        dest: /var/lib/tomcat/webapps/sample.war
        mode: 0777
      notify:
      - restart tomcat
  handlers:
    - name: restart tomcat
      service: name=tomcat state=restarted
